# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: person.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='person.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0cperson.proto\"X\n\rPersonMessage\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x12\n\nfirst_name\x18\x02 \x01(\t\x12\x11\n\tlast_name\x18\x03 \x01(\t\x12\x14\n\x0c\x63ompany_name\x18\x04 \x01(\t\"<\n\x19PersonMessageListResponse\x12\x1f\n\x07persons\x18\x01 \x03(\x0b\x32\x0e.PersonMessage\"\x1f\n\x10PersonIDsRequest\x12\x0b\n\x03ids\x18\x01 \x03(\x05\"\x1d\n\x0fPersonIDRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"&\n\x14PersonExistsResponse\x12\x0e\n\x06\x65xists\x18\x01 \x01(\x08\x32x\n\rPersonService\x12\x34\n\x03Get\x12\x11.PersonIDsRequest\x1a\x1a.PersonMessageListResponse\x12\x31\n\x06\x45xists\x12\x10.PersonIDRequest\x1a\x15.PersonExistsResponseb\x06proto3'
)




_PERSONMESSAGE = _descriptor.Descriptor(
  name='PersonMessage',
  full_name='PersonMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='PersonMessage.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='first_name', full_name='PersonMessage.first_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='last_name', full_name='PersonMessage.last_name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='company_name', full_name='PersonMessage.company_name', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=16,
  serialized_end=104,
)


_PERSONMESSAGELISTRESPONSE = _descriptor.Descriptor(
  name='PersonMessageListResponse',
  full_name='PersonMessageListResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='persons', full_name='PersonMessageListResponse.persons', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=106,
  serialized_end=166,
)


_PERSONIDSREQUEST = _descriptor.Descriptor(
  name='PersonIDsRequest',
  full_name='PersonIDsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ids', full_name='PersonIDsRequest.ids', index=0,
      number=1, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=168,
  serialized_end=199,
)


_PERSONIDREQUEST = _descriptor.Descriptor(
  name='PersonIDRequest',
  full_name='PersonIDRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='PersonIDRequest.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=201,
  serialized_end=230,
)


_PERSONEXISTSRESPONSE = _descriptor.Descriptor(
  name='PersonExistsResponse',
  full_name='PersonExistsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='exists', full_name='PersonExistsResponse.exists', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=232,
  serialized_end=270,
)

_PERSONMESSAGELISTRESPONSE.fields_by_name['persons'].message_type = _PERSONMESSAGE
DESCRIPTOR.message_types_by_name['PersonMessage'] = _PERSONMESSAGE
DESCRIPTOR.message_types_by_name['PersonMessageListResponse'] = _PERSONMESSAGELISTRESPONSE
DESCRIPTOR.message_types_by_name['PersonIDsRequest'] = _PERSONIDSREQUEST
DESCRIPTOR.message_types_by_name['PersonIDRequest'] = _PERSONIDREQUEST
DESCRIPTOR.message_types_by_name['PersonExistsResponse'] = _PERSONEXISTSRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PersonMessage = _reflection.GeneratedProtocolMessageType('PersonMessage', (_message.Message,), {
  'DESCRIPTOR' : _PERSONMESSAGE,
  '__module__' : 'person_pb2'
  # @@protoc_insertion_point(class_scope:PersonMessage)
  })
_sym_db.RegisterMessage(PersonMessage)

PersonMessageListResponse = _reflection.GeneratedProtocolMessageType('PersonMessageListResponse', (_message.Message,), {
  'DESCRIPTOR' : _PERSONMESSAGELISTRESPONSE,
  '__module__' : 'person_pb2'
  # @@protoc_insertion_point(class_scope:PersonMessageListResponse)
  })
_sym_db.RegisterMessage(PersonMessageListResponse)

PersonIDsRequest = _reflection.GeneratedProtocolMessageType('PersonIDsRequest', (_message.Message,), {
  'DESCRIPTOR' : _PERSONIDSREQUEST,
  '__module__' : 'person_pb2'
  # @@protoc_insertion_point(class_scope:PersonIDsRequest)
  })
_sym_db.RegisterMessage(PersonIDsRequest)

PersonIDRequest = _reflection.GeneratedProtocolMessageType('PersonIDRequest', (_message.Message,), {
  'DESCRIPTOR' : _PERSONIDREQUEST,
  '__module__' : 'person_pb2'
  # @@protoc_insertion_point(class_scope:PersonIDRequest)
  })
_sym_db.RegisterMessage(PersonIDRequest)

PersonExistsResponse = _reflection.GeneratedProtocolMessageType('PersonExistsResponse', (_message.Message,), {
  'DESCRIPTOR' : _PERSONEXISTSRESPONSE,
  '__module__' : 'person_pb2'
  # @@protoc_insertion_point(class_scope:PersonExistsResponse)
  })
_sym_db.RegisterMessage(PersonExistsResponse)



_PERSONSERVICE = _descriptor.ServiceDescriptor(
  name='PersonService',
  full_name='PersonService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=272,
  serialized_end=392,
  methods=[
  _descriptor.MethodDescriptor(
    name='Get',
    full_name='PersonService.Get',
    index=0,
    containing_service=None,
    input_type=_PERSONIDSREQUEST,
    output_type=_PERSONMESSAGELISTRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Exists',
    full_name='PersonService.Exists',
    index=1,
    containing_service=None,
    input_type=_PERSONIDREQUEST,
    output_type=_PERSONEXISTSRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_PERSONSERVICE)

DESCRIPTOR.services_by_name['PersonService'] = _PERSONSERVICE

# @@protoc_insertion_point(module_scope)
